### ISSUE TITLE
Remove automagical route lookup logic

### ISSUE THREAD

**Issue by joefitter** [UKHomeOffice/hof-bootstrap#33]
As a lib I should be as configurable as possible and not make assumptions about the dir structure of the application I am being used in.  Instead of expecting everything to be in `apps`, I should be passed an array of absolute paths, or at least the name of the directory to look in

**Comment by JoeChapman** [comment]
>  I should be passed an array of absolute paths, or at least the name of the directory to look in

IMO, I think an array of absolute paths is currently beyond the requirements of the users. I can see some value in allowing a user to override the default directory name for their apps/routes. However, some dictation is not necessarily a bad thing. After all, we want people to be able to quickly launch a service and not need to worry too much about what to name this or that. That said, I am not against this argument for a directory option.

Currently, if a user provides a `baseUrl` in the route, bootstrap will assume the views, fields and translations are in `./apps/<baseUrl>`. If the user provides a `name` in the route, bootstrap will assume the views, fields and translations are in `./apps/<name>`. Note: `name` clobbers `baseUrl` when looking up the views, fields and translations.

I think perhaps, the default value of the directory should be `./apps`, but that we provide another option, the name of which is to be decided. I'm open to PR's

**Comment by JoeChapman** [comment]
@easternbloc @bendiggle @gxxm @danielepolencic thoughts welcome please

**Comment by danielepolencic** [comment]
> IMO, I think an array of absolute paths is currently beyond the requirements of the users.

That.

I see where you're coming from, but unless there's someone asking for it I don't see any reason to waste effort.

Also all the project using HOF have `apps` as their default folder. No one bother to change that.

- https://github.com/UKHomeOffice/global-entry-customer/tree/master/apps
- https://github.com/UKHomeOffice/registered-traveller-customer/tree/master/apps
- https://github.com/UKHomeOffice/evw-self-serve/tree/master/apps
- https://github.com/UKHomeOffice/brp_app/tree/master/apps

Also the directory structure is consistent across all projects.

**Comment by easternbloc** [comment]
Does it largely matter? Tend to think it's a waste of time that can be spent in other areas.

**Comment by joefitter** [comment]
closes bcoz of all the haterz
