### ISSUE TITLE
The 'use' method does not work

### ISSUE THREAD

**Issue by daniel-ac-martin** [UKHomeOffice/hof-bootstrap#40]
The 'use' method is currently a bit pointless as by the time you have access to it the notFound and error middlewares have been added, which means that any that you add will never be executed.

Aside: Why not just expose the 'app' object from Express? (And perhap augment it with any extra functionality you wish to provide.)

**Comment by JoeChapman** [comment]
@daniel-ac-martin you are right. T'was a silly oversight and will be fixed

**Comment by JoeChapman** [comment]
Closed because we fixed. If this is still an issue, please open a new issue.
