### ISSUE TITLE
Shallow health check

### ISSUE THREAD

**Issue by JoeChapman** [UKHomeOffice/hof-bootstrap#42]
app.get('/healthz/ping', (req, res) => res.send(200));

**Comment by daniel-ac-martin** [comment]
:syringe: :question: :v: :100: :ok:

**Comment by easternbloc** [comment]
> :syringe: :question: :v: :100: :ok:

My thoughts exactly

**Comment by JoeChapman** [comment]
🐙

**Comment by daniel-ac-martin** [comment]
![Health insurance - It doesn't help if your doctor's an asshole.](http://quotesideas.com/wp-content/uploads/2015/10/Dr-House-motivational-quote.jpg)

**Comment by JoeChapman** [comment]
done
