### ISSUE TITLE
Error handler invoked without a translate function

### ISSUE THREAD

**Issue by JoeChapman** [UKHomeOffice/hof-bootstrap#7]
At https://github.com/UKHomeOffice/hof-bootstrap/blob/master/lib/defaults.js#L20 `hof.middleware.error` is invoked with `translate` and `logger`. However, `translate` is `undefined`.
The reason being that `require('hof').i18n` is in fact a function that when invoked returns an object with a translate function. 

Fix:
```
const i18n = require('hof').i18n({
  path: path_to_translations
})

...
translate: i18n.translate.bind(i18n)
...
```

Notes

1): path_to_translations should point to something like... `translations/__lng__/__ns__.json`
Such as:

```
apps/
  |- common/
    |- translations/
      |- en/ 
        |- default.json
```

2) `i18n.translate.bind(i18n)` the translate function must be explicitly bound to the i18n object. When the translate function is invoked without this context, its 'this` object appears to be `undefined`

**Comment by JoeChapman** [comment]
I think the error handler middleware should not be an option, but an integral part of the bootstrap function.

**Comment by danielepolencic** [comment]
> However, I think the error handler middleware should not be an option, but an integral part of the bootstrap function.

agree 👍 

Perhaps the translation path should configurable?
